xaj:
  param_name:
  - K
  - B
  - IM
  - UM
  - LM
  - DM
  - C
  - SM
  - EX
  - KI
  - KG
  - CS
  - L
  - CI
  - CG
  param_range:
    K:
    - 0.1
    - 1.0
    B:
    - 0.1
    - 0.4
    IM:
    - 0.01
    - 0.1
    UM:
    - 0.0
    - 20.0
    LM:
    - 60.0
    - 90.0
    DM:
    - 60.0
    - 120.0
    C:
    - 0.0
    - 0.2
    SM:
    - 1
    - 100.0
    EX:
    - 1.0
    - 1.5
    KI:
    - 0.0
    - 0.7
    KG:
    - 0.0
    - 0.7
    CS:
    - 0.0
    - 1.0
    L:
    - 1.0
    - 10.0
    CI:
    - 0.0
    - 0.9
    CG:
    - 0.98
    - 0.998
xaj_mz:
  param_name:
  - K
  - B
  - IM
  - UM
  - LM
  - DM
  - C
  - SM
  - EX
  - KI
  - KG
  - A
  - THETA
  - CI
  - CG
  param_range:
    K:
    - 0.1
    - 1.0
    B:
    - 0.1
    - 0.4
    IM:
    - 0.01
    - 0.1
    UM:
    - 0.0
    - 20.0
    LM:
    - 60.0
    - 90.0
    DM:
    - 60.0
    - 120.0
    C:
    - 0.0
    - 0.2
    SM:
    - 1.0
    - 100.0
    EX:
    - 1.0
    - 1.5
    KI:
    - 0.0
    - 0.7
    KG:
    - 0.0
    - 0.7
    A:
    - 0.0
    - 2.9
    THETA:
    - 0.0
    - 6.5
    CI:
    - 0.0
    - 0.9
    CG:
    - 0.98
    - 0.998
gr1a:
  param_name:
  - x
  param_range:
    x:
    - 0.13
    - 3.5
gr2m:
  param_name:
  - x1
  - x5
  param_range:
    x1:
    - 140
    - 2640
    x5:
    - 0.21
    - 1.31
gr3j:
  param_name:
  - x1
  - x2
  - x3
  param_range:
    x1:
    - -1
    - 1
    x2:
    - 0
    - 10
    x3:
    - 0
    - 1
gr4j:
  param_name:
  - x1
  - x2
  - x3
  - x4
  param_range:
    x1:
    - 100.0
    - 1200.0
    x2:
    - -5.0
    - 3.0
    x3:
    - 20.0
    - 300.0
    x4:
    - 1.1
    - 2.9
gr5j:
  param_name:
  - x1
  - x2
  - x3
  - x4
  - x5
  param_range:
    x1:
    - 100.0
    - 1200.0
    x2:
    - -5.0
    - 3.0
    x3:
    - 20.0
    - 300.0
    x4:
    - 1.1
    - 2.9
    x5:
    - 0
    - 1
gr6j:
  param_name:
  - x1
  - x2
  - x3
  - x4
  - x5
  - x6
  param_range:
    x1:
    - 100.0
    - 1200.0
    x2:
    - -5.0
    - 3.0
    x3:
    - 20.0
    - 300.0
    x4:
    - 1.1
    - 2.9
    x5:
    - 0
    - 1
    x6:
    - 0
    - 100
hymod:
  param_name:
  - cmax
  - bexp
  - alpha
  - ks
  - kq
  param_range:
    cmax:
    - 1.0
    - 500.0
    bexp:
    - 0.1
    - 2.0
    alpha:
    - 0.1
    - 0.99
    ks:
    - 0.001
    - 0.1
    kq:
    - 0.1
    - 0.99
