# Example configuration for XAJ with a custom event dataset.

data_cfgs:
  dataset: songliao_event
  source: local
  dataset_name: songliaorrevent
  time_unit: ["1D"]
  datasource_kwargs:
    version: null
    offset_to_utc: true
    trange4cache: null
    start_hour_in_a_day: 2
  basin_ids: ["songliao_21401550"]
  warmup_length: 30
  is_event_data: true
  variables: ["rain", "ES", "inflow", "flood_event"]
  train_period: ["2000-07-01", "2019-12-30"]
  valid_period: ["2021-08-21", "2021-08-28"]
  test_period: ["2020-07-01", "2023-12-30"]

model_cfgs:
  name: xaj
  params:
    source_type: sources
    source_book: HF
    kernel_size: 15

training_cfgs:
  algorithm: SCE_UA
  SCE_UA:
    rep: 1000
    ngs: 1000
    kstop: 500
    peps: 0.1
    pcento: 0.1
    random_seed: 1234
  loss: RMSE
  output_dir: results
  save_config: true

evaluation_cfgs:
  metrics: ["NSE", "RMSE", "KGE", "PBIAS"]
  save_results: true
  plot_results: true
